language: python
os: linux
dist: xenial
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
install:
  - pip install -r requirements.txt
jobs:
  include:
  - stage: checkout
    script: echo "nothing to do"
  - stage: test
    script: 
      - python3 -m pytest -v tests/test_dice.py
      - flake8
  - stage: build
    script: echo "nothing to do"
  - stage: deploy to staging
    script: skip
    deploy:
      provider: heroku
      strategy: api
      app: ci-me-dice-on-demand-staging
      api_key: "$HEROKU_AUTH_TOKEN"
      on: wwc-training-demo-python
  - stage: test staging
    script: curl http://ci-me-dice-on-demand-staging.herokuapp.com
  - stage: deploy to production
    script: /bin/true
    deploy:
      <<: *heroku
      app: ci-me-dice-on-demand-production
  - stage: test production
    script: curl http://ci-me-dice-on-demand-production.herokuapp.com
  - stage: notify
    script: echo "sending Slack notification..."
notifications:
  slack:
    rooms:
      secure: OEp35rJLJ86oX5LmOTp7SYisBMXBrsa/gMbpLWf3qkwBLt1L7fXhp+0L0p3xNTxY6d0BrbUZFe3tmu0d8sy81EEujkv2SC6WzWaCK4xMP9CdENHKCilJ9DANGb5UlURBN/Uk+RbA1pBr9gmqoXgM1nk+O1PlDPZ6knM5to0eYa1OHSvCLgCQI01vBo0iVc/xm5z27hhDdnT15q/eFuLG5mc/LnTqnntTEtdCmuNmA3AIl+p7Ywj6bS+poTchC3XvZiw0t9xK64i6ZDK0AUrL5yF20E5Uc/snAZ9BmNXwwYHZPmrKRIJo4PWrEYoVIxVytD2jN0WgoUwXyVbaDDH+KvyEMW+dqSPuzs+sYbKPxcVEQkyVK6SWvWPlad04wrXZ6Jkjb0vR9buEW2UV8bUWCUoTTMzdXjMvT4n1/BVz00OpRCRhAbU3y/JvIEowPhfXrz2KHv+fPpJLI1RvC9sm6dxe5s0GxyFc9y92qpTMzF8Mep9O3nPQHGK36/tGJzao4jyj3wXTkM1XvXEGOI2yJ8LBmS1lWopE4Vgu9x5X3hmoHs1UQVRENh1rchjnr7T5PF4Fi3N47RDhVl1blP08H7bnjpldL23UfXeh943NGBUKWmNFbQtD0LMpJnG1P1rMnlDgpebyaNnEMC/3Lmj+8W5H1wRPnRfRuJnpXq9kT/w=
    on_success: always
    on_failure: always
